
name: Build

on:
  push:
    tags:
        - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-09-22
          target: thumbv8m.main-none-eabihf
          override: true
          components: rustfmt, clippy

      - name: Create artifacts folder
        run: mkdir -p artifacts

      - name: Build default
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Copy default to artifacts
        run: cp target/thumbv8m.main-none-eabihf/release/dis-bootloader dis-bootloader.elf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dis-bootloader
          path: dis-bootloader.elf

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Test release
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./dis-bootloader.elf
          asset_name: bootloader.elf
          asset_content_type: application/octet-stream
    